Core: Improve script wording and text colours

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,7 +1,9 @@
 #!/bin/bash
 
 # Setup the message colour characters
+
 blue="\033[0;34m"
+yellow="\033[0;33m"
 red="\033[0;31m"
 end="\033[0m"
 
@@ -11,19 +13,20 @@ if [ $# -eq 0 ]; then
   exit 1
 fi
 
-echo "Running tests"
-${BASH_SOURCE%/*}/test
-if [ $? -ne 0 ]; then
-  echo "Tests failed, aborting deploy"
+# Ask for confirmation from the user before continuing
+read -p "$(echo -e $blue"Are you sure you want to create a new version ("$1")? (y/n) "$end)" ANSWER
+if [ "$ANSWER" != "y" ]; then
+  echo -e "${red}User cancelled, deploy aborted.${end}"
   exit 1
 fi
 
-# Ask for confirmation from the user before continuing
-read -p "Are you sure you want to create a new version ($1)? (y/n) " ANSWER
-if [ "$ANSWER" != "y" ]; then
-  echo -e "${red}Cancelled.${end}"
+echo -e "${blue}Running tests${end}"
+${BASH_SOURCE%/*}/test
+if [ $? -ne 0 ]; then
+  echo -e "${red}Tests failed, deploy aborted.${end}"
   exit 1
 fi
+
 
 echo -e "${blue}Updating the changelog...${end}"
 
